import { groq } from 'next-sanity';

// #region section-imports — generated by `yarn sections:register`
import faqSectionProjection from '@/sections/FaqSection/queries.groq';
import headerDisplaySectionProjection from '@/sections/HeaderDisplaySection/queries.groq';
import heroSectionProjection from '@/sections/HeroSection/queries.groq';
import mediaCardGridSectionProjection from '@/sections/MediaCardGridSection/queries.groq';
import mediaTagsSectionProjection from '@/sections/MediaTagsSection/queries.groq';
import numberedGridSectionProjection from '@/sections/NumberedGridSection/queries.groq';
import playerSelectSectionProjection from '@/sections/PlayerSelectSection/queries.groq';
import scheduleSectionProjection from '@/sections/ScheduleSection/queries.groq';
import specCardGridSectionProjection from '@/sections/SpecCardGridSection/queries.groq';
import twoColumnListSectionProjection from '@/sections/TwoColumnListSection/queries.groq';
// #endregion section-imports

/*
 * Joined here rather than interpolated one-per-line, so `yarn sections:register` has somewhere to
 * write that is outside the backticks — see the note below on why a marker cannot go inside them.
 *
 * `'\n  '` reproduces the template's own newline-plus-indent between interpolations exactly, so the
 * built query string is byte-identical to the hand-written version this replaced.
 */
const sectionProjections = [
  // #region section-projections
  faqSectionProjection,
  headerDisplaySectionProjection,
  heroSectionProjection,
  mediaCardGridSectionProjection,
  mediaTagsSectionProjection,
  numberedGridSectionProjection,
  playerSelectSectionProjection,
  scheduleSectionProjection,
  specCardGridSectionProjection,
  twoColumnListSectionProjection
  // #endregion section-projections
].join('\n  ');

/*
 * `sectionFields.themeOptions` was missing from this projection, and the omission was silent.
 *
 * Every section reads its theme through `getSectionTheme(props)`, which looks at
 * `sectionFields.themeOptions.theme` — a key this projection never returned. The Studio's Light/Dark
 * radio therefore changed nothing on a published page and every section fell through to its
 * component-level fallback. It does not show up in Storybook either, because `sectionStory.tsx`
 * injects the theme into args from the toolbar global, so a section looks correctly themeable there
 * while being fixed in production.
 *
 * Kept as a TypeScript comment rather than one inside the template literal: everything between the
 * backticks is sent to the Sanity API, so a comment there is query weight (`yarn audit:projections`
 * counts it) and depends on GROQ's comment syntax rather than on TypeScript's.
 */
const sectionsProjection = groq`{
  _key,
  _type,
  ${sectionProjections}
  sectionFields {
    spacingOptions {
      removeTopSpacing,
      removeBottomSpacing
    },
    themeOptions {
      theme
    }
  }
}`;

export default sectionsProjection;
