// AUTO-GENERATED by `yarn storybook:fixtures`. Do not edit by hand.
import faqSection from './faqSection.json';

const fixtures: Record<string, unknown> = {
  faqSection
};

export default fixtures;
