// AUTO-GENERATED by `yarn storybook:fixtures`. Do not edit by hand.
import closingCtaSection from './closingCtaSection.json';
import embedSection from './embedSection.json';
import faqSection from './faqSection.json';
import gridSection from './gridSection.json';
import headerHeroSection from './headerHeroSection.json';
import headerSimpleSection from './headerSimpleSection.json';
import logosSection from './logosSection.json';
import mediaSection from './mediaSection.json';
import threeColBlogSection from './threeColBlogSection.json';
import threeColSection from './threeColSection.json';
import twoColDefaultSection from './twoColDefaultSection.json';

const fixtures: Record<string, unknown> = {
  closingCtaSection,
  embedSection,
  faqSection,
  gridSection,
  headerHeroSection,
  headerSimpleSection,
  logosSection,
  mediaSection,
  threeColBlogSection,
  threeColSection,
  twoColDefaultSection
};

export default fixtures;
