// AUTO-GENERATED by `yarn storybook:fixtures`. Do not edit by hand.
import closingCtaSection from './closingCtaSection.json';
import faqSection from './faqSection.json';
import headerDisplaySection from './headerDisplaySection.json';
import heroSection from './heroSection.json';
import mediaCardGridSection from './mediaCardGridSection.json';
import numberedGridSection from './numberedGridSection.json';
import playerSelectSection from './playerSelectSection.json';
import scheduleSection from './scheduleSection.json';
import specCardGridSection from './specCardGridSection.json';
import twoColumnListSection from './twoColumnListSection.json';

const fixtures: Record<string, unknown> = {
  closingCtaSection,
  faqSection,
  headerDisplaySection,
  heroSection,
  mediaCardGridSection,
  numberedGridSection,
  playerSelectSection,
  scheduleSection,
  specCardGridSection,
  twoColumnListSection
};

export default fixtures;
