// Generated by `yarn sections:register` from the contents of `sections/`. Do not edit by hand.
// Add or remove a section folder, then re-run the command.

export const pageSections = [
  { type: 'faqSection' },
  { type: 'headerDisplaySection' },
  { type: 'mediaTagsSection' },
  { type: 'scheduleSection' },
  { type: 'specCardGridSection' },
  { type: 'twoColumnListSection' }
];
