// Generated by `yarn sections:register` from the contents of `sections/`. Do not edit by hand.
// Add or remove a section folder, then re-run the command.

export const pageSections = [
  { type: 'closingCtaSection' },
  { type: 'faqSection' },
  { type: 'headerDisplaySection' },
  { type: 'heroSection' },
  { type: 'mediaCardGridSection' },
  { type: 'mediaTagsSection' },
  { type: 'numberedGridSection' },
  { type: 'playerSelectSection' },
  { type: 'scheduleSection' },
  { type: 'specCardGridSection' },
  { type: 'twoColumnListSection' }
];
