// Regenerates the four section registrations from the contents of `sections/`.
//
// Run with: yarn sections:register        (writes)
//           yarn sections:register --check (verifies, writes nothing, exits 1 on drift)
//
// A section is only wired up when it appears in four places (CLAUDE.md § Section Architecture), and
// every half-registration fails silently — `registration.test.ts` exists because of it. Those four
// places are pure functions of the folder name, so hand-editing them is transcription, and
// transcription is where the silence comes from.
//
// It also makes them the whole reason parallel section branches conflict. Each is a short,
// alphabetically sorted list; git's three-way merge carries three lines of context, so two branches
// inserting into a four-line file always collide. Because the files are *derivable*, that conflict
// is not a real disagreement — regenerating resolves it. `/batch-tickets --parallel` does exactly
// that in its merge train.
//
// The output stays committed rather than gitignored. `audit-sections.ts`, `audit-projections.ts` and
// `generate-fixtures.ts` all import these modules and run under `tsx`, which is esbuild-on-Node with
// no bundler — so an `import.meta.glob` barrel (which Turbopack and Vite both support) would break
// all three, including the `story-fixture-checker` pass inside `/commit` and `/pr`. Static files work
// under every runtime this repo has.

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { companionExports } from './lib/companionExports';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');

const CHECK = process.argv.includes('--check');

/** Every name a section needs, all derived from its folder. */
interface Section {
  /** `TwoColumnListSection` — the folder, the component export, and the story's subject. */
  folder: string;
  /** `twoColumnListSection` — the Sanity `_type`, the schema file, and the schema's named export. */
  type: string;
}

/*
 * Sorted by codepoint, never `localeCompare`.
 *
 * `localeCompare` with no locale argument uses the runtime's default, so two machines can order the
 * same folders differently — which would make `--check` report drift on one developer's box and not
 * another's. A generator whose output depends on the environment cannot be a merge-conflict
 * resolver.
 */
const sections: Section[] = readdirSync(join(root, 'sections'), { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && /^[A-Z][A-Za-z0-9]*Section$/.test(entry.name))
  .map((entry) => ({ folder: entry.name, type: entry.name.charAt(0).toLowerCase() + entry.name.slice(1) }))
  .toSorted((a, b) => (a.folder < b.folder ? -1 : 1));

/*
 * A folder missing any of its three sources is a hard error, not a skip.
 *
 * Generating an import for a file that does not exist turns a half-built section into a build
 * failure in four unrelated files, none of which name the section. Failing here names it once.
 */
const missing = sections.flatMap(({ folder, type }) =>
  [
    `sections/${folder}/index.tsx`,
    `sections/${folder}/queries.groq.ts`,
    `tools/sanity/schema/sections/${type}.ts`
  ].filter((relative) => !existsSync(join(root, relative)))
);

if (missing.length > 0) {
  process.stderr.write(
    `Incomplete section(s) — cannot generate registrations:\n${missing.map((m) => `  missing ${m}`).join('\n')}\n`
  );
  process.exit(1);
}

/*
 * Sub-types are not derivable, so say so rather than silently dropping them.
 *
 * A schema file may export companions alongside the section (`export { gridSection, gridCard }`).
 * The generated import names only the section, so a companion referenced in the schema array's
 * `// Objects` block becomes an undefined identifier — caught by `yarn ts:check`, but with an error
 * that names the identifier rather than the cause. Warning here names the cause.
 *
 * The fix is to move companions into `tools/sanity/schema/objects/`, which keeps the generated
 * region generated. Deliberately a warning, not an error: a section may legitimately have them while
 * that move is pending.
 */
const companions = sections.flatMap(({ type }) => {
  const source = readFileSync(join(root, 'tools/sanity/schema/sections', `${type}.ts`), 'utf8');
  const exported = companionExports(source, type);
  return exported.length > 0 ? [`  ${type}.ts also exports: ${exported.join(', ')}`] : [];
});

if (companions.length > 0) {
  process.stderr.write(
    `Sub-type exports are not written by this generator — register them in the '// Objects' block by hand,\nor move them to tools/sanity/schema/objects/:\n${companions.join('\n')}\n`
  );
}

const BANNER = (command: string) =>
  `// Generated by \`yarn sections:register\` from the contents of \`sections/\`. Do not edit by hand.\n// Add or remove a section folder, then re-run the command.${command}\n`;

/** The two files this owns outright, emitted whole. */
const wholeFiles: Record<string, string> = {
  'sections/index.ts': `${BANNER('')}\n${sections.map(({ folder }) => `export { default as ${folder} } from './${folder}';`).join('\n')}\n`,

  'tools/sanity/helpers/sections.ts': `${BANNER('')}\nexport const pageSections = [\n${sections
    .map(({ type }) => `  { type: '${type}' }`)
    .join(',\n')}\n];\n`
};

/*
 * The two files it only owns a region of, rewritten between sentinels.
 *
 * `schema/index.ts` and `sections.groq.ts` both carry a great deal of hand-written content the
 * generator has no business touching, so it replaces marked spans instead of whole files. The
 * sentinels are `#region`/`#endregion` because editors fold on them, which makes the generated span
 * visibly inert rather than merely commented.
 *
 * Note where the projection sentinels sit: **outside** the `groq` template literal. Everything
 * between those backticks is sent to the Sanity API, so a marker in there would be query weight that
 * `yarn audit:projections` counts — the same reason the file's own rationale is a TypeScript comment.
 */
interface Region {
  file: string;
  marker: string;
  body: string;
}

const regions: Region[] = [
  {
    file: 'tools/sanity/schema/index.ts',
    marker: 'section-imports',
    body: sections.map(({ folder, type }) => `import { ${type} } from './sections/${type}';`).join('\n')
  },
  {
    file: 'tools/sanity/schema/index.ts',
    marker: 'section-types',
    body: sections.map(({ type }) => `  ${type}`).join(',\n')
  },
  {
    file: 'tools/sanity/projections/common/sections.groq.ts',
    marker: 'section-imports',
    body: sections
      .map(({ folder, type }) => `import ${type}Projection from '@/sections/${folder}/queries.groq';`)
      .join('\n')
  },
  {
    file: 'tools/sanity/projections/common/sections.groq.ts',
    marker: 'section-projections',
    body: sections.map(({ type }) => `  ${type}Projection`).join(',\n')
  }
];

const applyRegion = (source: string, { file, marker, body }: Region): string => {
  const pattern = new RegExp(`([ \\t]*// #region ${marker}[^\\n]*\\n)[\\s\\S]*?([ \\t]*// #endregion ${marker})`);
  if (!pattern.test(source)) {
    process.stderr.write(`Missing '// #region ${marker}' … '// #endregion ${marker}' sentinels in ${file}\n`);
    process.exit(1);
  }
  return source.replace(pattern, `$1${body}\n$2`);
};

const pending = new Map<string, string>();

for (const [relative, contents] of Object.entries(wholeFiles)) {
  pending.set(relative, contents);
}

for (const region of regions) {
  const absolute = join(root, region.file);
  const current = pending.get(region.file) ?? readFileSync(absolute, 'utf8');
  pending.set(region.file, applyRegion(current, region));
}

const changed: string[] = [];

for (const [relative, contents] of pending) {
  const absolute = join(root, relative);
  if (existsSync(absolute) && readFileSync(absolute, 'utf8') === contents) {
    continue;
  }
  changed.push(relative);
  if (!CHECK) {
    writeFileSync(absolute, contents);
  }
}

const summary = `${sections.length} section${sections.length === 1 ? '' : 's'}: ${sections.map((s) => s.type).join(', ')}`;

if (CHECK) {
  if (changed.length > 0) {
    process.stderr.write(
      `Section registrations are stale — run \`yarn sections:register\`:\n${changed.map((c) => `  ${c}`).join('\n')}\n`
    );
    process.exit(1);
  }
  process.stdout.write(`Section registrations up to date — ${summary}\n`);
} else {
  process.stdout.write(
    changed.length > 0
      ? `Rewrote ${changed.length} file${changed.length === 1 ? '' : 's'} — ${summary}\n${changed.map((c) => `  ${c}`).join('\n')}\n`
      : `Section registrations already up to date — ${summary}\n`
  );
}
