import type { SchemaTypeDefinition } from 'sanity';

import headerDocument from './documents/headerDocument';
// Documents
import page from './documents/page';
import { player, playerMeterStat, playerTextStat } from './documents/player';
import route from './documents/route';
import rsvp from './documents/rsvp';
import settings from './documents/settings';
import { socialMediaDocument, socialMediaItem } from './documents/socialMediaDocument';
import weddingSettings from './documents/weddingSettings';
import buttonElement from './elements/button';
// Common
import icon from './elements/icon';
import { imageElementAdvanced, imageElementSimple } from './elements/image';
import linkElement from './elements/link';
import slugElement from './elements/slug';
import title from './elements/title';
// Objects
import {
  blockContentSimple,
  blockContentStandard,
  blockContentAdvanced,
  blockContentImage,
  blockContentVideo,
  blockContentButtons
} from './objects/blockContent';
import divider from './objects/divider';
import { header, navLink } from './objects/header';
import redirect from './objects/redirect';
import { sectionFields, spacingOptions, themeOptions } from './objects/sectionFields';
import seo from './objects/seo';
// #region section-imports — generated by `yarn sections:register`
import { closingCtaSection } from './sections/closingCtaSection';
import { faqSection } from './sections/faqSection';
import { headerDisplaySection } from './sections/headerDisplaySection';
import { heroSection } from './sections/heroSection';
import { mediaCardGridSection } from './sections/mediaCardGridSection';
import { mediaTagsSection } from './sections/mediaTagsSection';
import { numberedGridSection } from './sections/numberedGridSection';
import { playerSelectSection } from './sections/playerSelectSection';
import { scheduleSection } from './sections/scheduleSection';
import { specCardGridSection } from './sections/specCardGridSection';
import { twoColumnListSection } from './sections/twoColumnListSection';
// #endregion section-imports

const schema: SchemaTypeDefinition[] = [
  // Documents
  headerDocument,
  page,
  player,
  route,
  rsvp,
  settings,
  socialMediaDocument,
  weddingSettings,

  // Objects
  blockContentSimple,
  blockContentStandard,
  blockContentAdvanced,
  blockContentImage,
  blockContentVideo,
  blockContentButtons,
  divider,
  header,
  navLink,
  playerTextStat,
  playerMeterStat,
  redirect,
  seo,
  sectionFields,
  socialMediaItem,
  spacingOptions,
  themeOptions,

  // Elements
  icon,
  title,
  imageElementSimple,
  imageElementAdvanced,
  linkElement,
  buttonElement,
  slugElement,

  /*
   * Sections — generated by `yarn sections:register`. Keep this region **last** in the array: its
   * final entry carries no trailing comma, because oxfmt is configured to strip one.
   */
  // #region section-types
  closingCtaSection,
  faqSection,
  headerDisplaySection,
  heroSection,
  mediaCardGridSection,
  mediaTagsSection,
  numberedGridSection,
  playerSelectSection,
  scheduleSection,
  specCardGridSection,
  twoColumnListSection
  // #endregion section-types
];

export default schema;
